name: Build and test using Docker

on:
- pull_request
- push

jobs:
  build_and_test:
    name: Build and test using Docker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1

      - name: Set up Python 3.12
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236  # v4.7.1
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |-
          pip install \
            --disable-pip-version-check \
            --user \
            --no-warn-script-location \
            'PyYAML==5.3.1' \
            'urllib3<2' \
            docker-compose
          echo "PATH=${HOME}/.local/bin:${PATH}" >> "${GITHUB_ENV}"

      - name: Configure Docker environment
        run: |-
          docker network create --internal ssl-reverse-proxy
          tee .env <<-EOF
            JAWANNDENN_POSTGRES_NAME=jawanndenn111
            JAWANNDENN_POSTGRES_USER=jawanndenn222
            JAWANNDENN_POSTGRES_PASSWORD=jawanndenn333
            JAWANNDENN_SECRET_KEY=jawanndenn444
          EOF

      - name: Build Docker image
        run: |-
          docker-compose build

      - name: Run tests using Docker
        run: |-
          docker-compose run jawanndenn test -v2
