name: Detect .dockerignore out-of-sync with git ls-files

on:
- pull_request
- push

jobs:
  dockerignore_detect_out_of_sync:
    name: Detect .dockerignore out-of-sync with git ls-files
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3.6.0

      - name: Check for out-of-sync .dockerignore
        run: |-
          diff -U0 <(./generate_whitelist_dockerignore_file.sh) .dockerignore
