name: Detect .dockerignore out-of-sync with git ls-files

on:
  pull_request:
  push:
  schedule:
    - cron: '0 16 * * 5'  # Every Friday 4pm
  workflow_dispatch:

jobs:
  dockerignore_detect_out_of_sync:
    name: Detect .dockerignore out-of-sync with git ls-files
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f  # v4.1.3

      - name: Check for out-of-sync .dockerignore
        run: |-
          diff -U0 <(./generate_whitelist_dockerignore_file.sh) .dockerignore
